package olmo.wellness.android.ui.screen.navigation

sealed class ScreenName(val route: String){
    object SignInEmailScreen: ScreenName("sign_in_by_email_screen")
    object SignInByPhoneScreen: ScreenName("sign_in_by_phone_screen")
    object HomeScreen: ScreenName("home_screen")
    object DeepLinkScreen: ScreenName("deeplink_screen")
    object OnBoardSignUpScreen: ScreenName("onboard_sign_up_screen")
    object VerifyCodeScreen : ScreenName("verify_code_screen")
    object VerifyCodeSuccessScreen : ScreenName("verify_code_success_screen")
    object ForgetPasswordScreen : ScreenName("forgot_password_screen")
    object CreatePasswordScreen : ScreenName("create_password_screen")

    object LivestreamPOCScreen : ScreenName("livestream_poc_screen")
    object LivestreamStreamerScreen : ScreenName("livestream_streamer_screen")
    object PermissionLivestreamStreamerScreen : ScreenName("permission_livestream_streamer_screen")
    object CreateScheduleLiveStreamScreen : ScreenName("create_schedule_livestream_screen")
    object StatisticsLiveStreamScreen : ScreenName("statistics_livestream_screen")

    object SellerHubScreen: ScreenName("seller_hub_screen")
    object SettingsScreen: ScreenName("settings_screen")
    object ProfileSettingScreen: ScreenName("profile_setting_screen")
    object SellerVerificationStep1Screen: ScreenName("seller_verification_step_1_screen")
    object UserRegistered: ScreenName("user_registered_screen")
    object TestComposeScreen: ScreenName("test_compose_screen")
    object AccountSettingScreen: ScreenName("account_setting_screen")
    object VerificationStep2SuccessScreen: ScreenName("verification_success_step2_screen")
    object VerificationSummarySuccess : ScreenName("verification_success_summary_screen")
    object SellerVerificationStep2Screen: ScreenName("seller_verification_step_2_screen")
    object IdentifySuccessScreen : ScreenName("identify_success_screen")

    /* MyProfile */
    object MyProfileDashboardScreen : ScreenName("my_profile_dashboard_screen")
    object AccountSwitcherScreen : ScreenName("account_switcher_screen")
    object SocialMediaScreen : ScreenName("social_media_screen")

    object AuthenticatorScreen : ScreenName("authenticator_screen")
    object AuthenticatorInputCodeScreen : ScreenName("authenticator_input_code_screen")
    object WarningDeleteAccountScreen : ScreenName("warning_delete_account_screen")
    object SelectReasonDeleteAccountScreen: ScreenName("select_reason_delete_account_screen")

    object ChatSettingScreen: ScreenName("chat_setting_screen")
    object AutoReplyScreen: ScreenName("auto_reply_screen")
    object MessageShortcutScreen: ScreenName("message_shortcut_screen")
    object DetailMessageShortcutScreen: ScreenName("detail_message_shortcut_screen")
    object ShareProfileScreen : ScreenName("share_profile_screen")
    object ContactSyncingScreen : ScreenName("contact_syncing_screen")
    object ChooseLanguageScreen : ScreenName("choose_language_screen")
    object NotificationSettingScreen : ScreenName("notification_setting_screen")
    object PrivacySettingsScreen : ScreenName("privacy_settings_screen")
    object BlockContacts : ScreenName("block_contacts_screen")
    object BlockContactsSearch : ScreenName("block_contacts_search_screen")
    object CreateMessageShortcutScreen : ScreenName("create_message_shortcut_screen")
    object NewsFeedsHomeScreen : ScreenName("news_feed_home_screen")
    object OnboardLiveScreen : ScreenName("onboard_live_screen")
    object ExploreLiveStreamScreen : ScreenName("explore_playback_live_screen")
    object PlayBackOnLiveStreamScreen : ScreenName("playback_on_live_screen")
    object ConversationListContentScreen : ScreenName("conversation_list_screen")
    object ConversationDetailScreen : ScreenName("conversation_detail_screen")
    object EventDetailScreen : ScreenName("event_detail_screen")
    object NotificationHomeScreen : ScreenName("notification_home_screen")
    object SummaryLiveStreamScreen : ScreenName("summary_live_stream_screen")
    object LiveSchedulingScreen : ScreenName("live_scheduling_screen")
    object CalendarScreen: ScreenName("calendar_scheduling_screen")
    object BusinessHoursScreen : ScreenName("business_hours_screen")
    object SubCategoriesScreen : ScreenName("sub_categories_screen")
    object SeeAllUpComingScreen : ScreenName("see_all_upcoming_screen")
    object SeeAllFilterLiveStreamScreen : ScreenName("see_all_filter_live_screen")
    object FollowingProfileScreen : ScreenName("following_profile_screen")

    object InfoPackageScreen : ScreenName("info_package_screen")
    object KeplerBalanceSellerScreen : ScreenName("kepler_balance_seller_screen")
    object KeplerBalanceBuyerScreen : ScreenName("kepler_balance_buyer_screen")
    object InfoPackageDetailScreen : ScreenName("info_detail_package_screen")
    object PaymentProcessScreen : ScreenName("payment_process_screen")
    object PrivacyScreen : ScreenName("privacy_screen")
    object MyDashBoardBookingScreen : ScreenName("my_dashboard_booking_screen")
    object MyServiceBookingDetails : ScreenName("my_dashboard_details_booking_screen")

}