package olmo.wellness.android.domain.model.defination

enum class CountryType(type: String) {
    BUSINESS_COUNTRY_STEP1("BUSINESS_COUNTRY_STEP1"),
    ADDRESS_COUNTRY_STEP1("ADDRESS_COUNTRY_STEP1"),
    CITIZEN_COUNTRY_STEP2("CITIZEN_COUNTRY_STEP2"),
    ISSUE_COUNTRY_STEP2("ISSUE_COUNTRY_STEP2"),
    ADDRESS_COUNTRY_STEP3("ADDRESS_COUNTRY_STEP3"),
}